### PR TITLE
Release v1.0.0-rc.5

### PR DESCRIPTION
**Pull request by m-mohr**
Please review this release.

Changes:
- **Breaking:** TypeScript declarations have moved from src/*.d.ts to openeo.d.ts
- Improved TypeScript support @christophfriedrich @jneijt
- Improved documentation
- Expose content media type for computeResult() as `type`
- Improved and new examples @christophfriedrich

### CODE REVIEW

**Review by jneijt — APPROVED** [review]
Looks good to me! Just re-ran the typescript build with the mobile app and everything is running fine 👍

**Comment by m-mohr** [comment]
Thank you, @jneijt.

My last commit to update the README has dismissed the approval. Could you approve again, please? :-)

**Review by jneijt — APPROVED** [review]

**Comment by jneijt** [comment]
Done :-)

**Comment by christophfriedrich** [comment]
With the examples properly in there and also the correct version numbers now it seems complete :ok_hand:

**Review by christophfriedrich — APPROVED** [review]

**Pull request merged**
